.TH pabrowse 1 User Manuals
.SH NAME
pabrowse \- List PulseAudio sound servers on the network
.SH SYNOPSIS
\fBpabrowse
\f1
.SH DESCRIPTION
\fIpabrowse\f1 lists all PulseAudio sound servers on the local network that are being announced with Zeroconf/Avahi.

This program takes no command line arguments.
.SH AUTHORS
The PulseAudio Developers <mzchyfrnhqvb (at) 0pointer (dot) net>; PulseAudio is available from \fBhttp://pulseaudio.org/\f1
.SH SEE ALSO
\fBpulseaudio(1)\f1, \fBavahi-daemon(8)\f1
