.TH pacmd 1 User Manuals
.SH NAME
pacmd \- Reconfigure a PulseAudio sound server during runtime
.SH SYNOPSIS
\fBpacmd
\f1
.SH DESCRIPTION
This tool can be used to introspect or reconfigure a running PulseAudio sound server during runtime. It connects to the sound server and offers a simple live shell that can be used to enter the commands also understood in the \fIdefault.pa\f1 configuration scripts.

This program takes no command line options.
.SH AUTHORS
The PulseAudio Developers <mzchyfrnhqvb (at) 0pointer (dot) net>; PulseAudio is available from \fBhttp://pulseaudio.org/\f1
.SH SEE ALSO
\fBpulseaudio(1)\f1, \fBpactl(1)\f1, \fBdefault.pa(5)\f1
